# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd652d75d660c6e21a782040321afdc50f0d9d48cdee534d38dceb550e1a6fd98c4f7afa627b469a267cdeaab315e2263e64a499db0c82ad1a850c1a48736cc

test:
  secret_key_base: a5bb33de500b92cb8366f2abe044f28c69e4b6f732cba7a9e920eccad408f0c0b77471d96fab677f64a8c957d74a19101f7e623a05f3b16f1c21046cb75f0a0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
